DECIDED = {
    "01-landing": ["#1 Headline stays: \"Practise how you think, not what you memorised.\" A second line is A/B tested after launch.",
                   "#2 The Day-1 case is playable before sign-up; progress is saved on register."],
    "02-onboarding": ["#3 Current role is asked of switchers only.",
                      "#4 The plan shows weeks (\"about 14 weeks\") with an optional \"show dates\" toggle."],
    "03-day1": ["#5 The limit stays at 3 questions.",
                "#6 Order: case, then sign-up, then onboarding, then home."],
    "04-dashboard": ["#7 Bottom bar keeps 5 items; Career shows a light preview until Stage 2.",
                     "#8 The skill map sits second, under the next-action card."],
    "05-concept": ["#9 The Attempt can be skipped with \"I don't know\"; it is logged.",
                   "#10 The \"when it misleads\" line stays."],
    "06-quiz": ["#11 Confidence stays, labelled Guessing / Fairly sure / Very sure, with the percentage small.",
                "#12 No immediate retry; the item resurfaces in Daily Reps."],
    "07-tree-builder": ["#13 Tap-and-place only at launch; no free typing of nodes.",
                        "#14 Appears in M3 and M6, plus an optional, ungraded tool inside cases."],
    "08-inbox": ["#15 Choose the variant first; switching later resets hints and asks.",
                 "#16 The Professional variant is shown locked (Plus) on Free."],
    "09-stakeholder": ["#17 The menu shows 4 questions at a time, refreshed after each ask.",
                       "#18 The results page lists the most useful questions the learner asked."],
    "10-data-room": ["#19 Three misses, then a list of exhibit titles is offered.",
                     "#20 CSV download for Student, and for Professional once an exhibit is requested."],
    "11-submit": ["#21 Hints: one per tap.",
                  "#22 Level names: Starting, Developing, Solid, Strong.",
                  "#23 The ₹999 capstone review button sits here after submission, plus a link from the portfolio item."],
    "12-opponent": ["#24 No skip; the learner can stop and resume later.",
                    "#25 Two personas in core modules; three in ICs and capstones."],
    "13-thinking-record": ["#26 Labels: \"First take\" (field 2) and \"What would change my mind\" (field 11).",
                           "#27 Editable after saving; version 1 is kept."],
    "14-portfolio": ["#28 A handle is allowed; real name is optional.",
                     "#29 The learner picks which levels show publicly, per item."],
    "15-interview-lab": ["#30 Text is the default; voice is optional.",
                         "#31 The tab is visible but locked on Free."],
    "16-story-bank": ["#32 One free story.",
                      "#33 Résumé bullets at launch: template-based, confirmed facts only."],
    "17-jd-decoder": ["#34 A JD is kept only when the learner taps Save.",
                      "#35 No match percentage; show matched and gap skills."],
    "18-pricing": ["#36 Annual first (₹2,499/yr, about ₹208/mo); monthly secondary.",
                   "#37 7-day refund on the first purchase.",
                   "#38 The founding offer is for waitlist members only (first 500, via a code)."],
    "19-personal-problem": ["#39 Built by new batch P14b in week 7 (uses 1 buffer slot).",
                            "#40 Unlimited on Free; Plus adds the challenge step.",
                            "#41 Privacy note: \"Don't include confidential company or personal data.\""],
}
